import './globals.css'
import localFont from 'next/font/local';
import {NextFont} from "next/dist/compiled/@next/font";


// const fonts: NextFont = localFont({
//     src: "./7segment.woff2"
// })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        {/*<body className={inter.className}>{children}</body>*/}
        <body className={"h-screen w-screen"}>{children}</body>
        {/*<body className={"h-screen w-screen " + fonts.className}>{children}</body>*/}
        </html>
    )
}
